const questions = {
    javascript: {
        easy: [
            {
                question: "Which keyword is used to declare a block-scoped variable in modern JavaScript?",
                answers: ["var", "let", "define", "dim"],
                correct: 1
            },
            {
                question: "What does `console.log(typeof 'Hello')` output?",
                answers: ["object", "text", "string", "undefined"],
                correct: 2
            },
            {
                question: "Which symbol is used for single-line comments in JavaScript?",
                answers: ["<!--", "//", "/*", "#"],
                correct: 1
            },
            {
                question: "Which array method adds one or more elements to the end of an array?",
                answers: ["shift()", "push()", "unshift()", "pop()"],
                correct: 1
            },
            {
                question: "What is the correct way to write an IF statement in JavaScript?",
                answers: ["if x = 5 then", "if (x === 5)", "if x == 5", "if {x === 5}"],
                correct: 1
            },
            {
                question: "Which method converts a JSON string into a JavaScript object?",
                answers: ["JSON.stringify()", "JSON.parse()", "JSON.toObject()", "JSON.serialize()"],
                correct: 1
            },
            {
                question: "What value does an uninitialized variable hold in JavaScript?",
                answers: ["null", "0", "false", "undefined"],
                correct: 3
            },
            {
                question: "Which operator is used for strict equality (checks both value and type)?",
                answers: ["==", "=", "===", "equals"],
                correct: 2
            },
            {
                question: "How do you round a number to the nearest integer in JavaScript?",
                answers: ["Math.floor()", "Math.round()", "Math.ceil()", "Math.trunc()"],
                correct: 1
            },
            {
                question: "Which built-in function pops up a dialog box with a message and an OK button?",
                answers: ["alert()", "prompt()", "confirm()", "message()"],
                correct: 0
            }
        ],
        medium: [
            {
                question: "What is the result of `0.1 + 0.2 === 0.3` in JavaScript?",
                answers: ["true", "false", "TypeError", "NaN"],
                correct: 1
            },
            {
                question: "Which array method returns a new array with all elements that pass a test function?",
                answers: ["map()", "forEach()", "filter()", "reduce()"],
                correct: 2
            },
            {
                question: "What does the `this` keyword refer to inside a regular function in strict mode when called without context?",
                answers: ["window object", "undefined", "null", "globalThis"],
                correct: 1
            },
            {
                question: "What will `console.log(3 + '3')` display?",
                answers: ["6", "NaN", "33", "TypeError"],
                correct: 2
            },
            {
                question: "Which statement correctly describes arrow functions in JavaScript?",
                answers: [
                    "They have their own binding to `this`",
                    "They cannot be used as constructors with `new`",
                    "They automatically bind `arguments` object",
                    "They must always use explicit return statements"
                ],
                correct: 1
            },
            {
                question: "How do you create a shallow copy of an array named `arr` using ES6 syntax?",
                answers: [
                    "const copy = arr.clone()",
                    "const copy = [...arr]",
                    "const copy = arr.copy()",
                    "const copy = Array.fromObject(arr)"
                ],
                correct: 1
            },
            {
                question: "What does `Array.prototype.reduce()` return if no initial value is provided for an array with items?",
                answers: [
                    "0",
                    "undefined",
                    "The accumulative result starting with the first array element",
                    "A new array"
                ],
                correct: 2
            },
            {
                question: "What is the primary difference between `null` and `undefined`?",
                answers: [
                    "null is an object type; undefined means a variable has been declared but not assigned",
                    "undefined is an explicit assignment; null is auto-generated by JS",
                    "There is no difference; they are exact aliases",
                    "typeof null returns 'null', while typeof undefined returns 'undefined'"
                ],
                correct: 0
            },
            {
                question: "Which method stops the execution of an event's default action in the browser?",
                answers: [
                    "event.stopPropagation()",
                    "event.preventDefault()",
                    "event.stopImmediatePropagation()",
                    "event.cancelBubble()"
                ],
                correct: 1
            },
            {
                question: "What does `Promise.all()` do if one of the promises passed to it rejects?",
                answers: [
                    "It waits for all other promises to resolve first",
                    "It immediately rejects with the reason of the first rejected promise",
                    "It returns an array containing null for the rejected promise",
                    "It converts the rejected promise to undefined"
                ],
                correct: 1
            },
            {
                question: "What will `console.log(typeof NaN)` output?",
                answers: ["NaN", "undefined", "number", "object"],
                correct: 2
            },
            {
                question: "How do you check if a key 'age' exists in an object named `user`?",
                answers: [
                    "user.hasKey('age')",
                    "'age' in user",
                    "user.contains('age')",
                    "user.exists('age')"
                ],
                correct: 1
            },
            {
                question: "Which keyword is used to pause execution in a generator function?",
                answers: ["pause", "yield", "await", "defer"],
                correct: 1
            },
            {
                question: "What is the return value of `Boolean('false')`?",
                answers: ["false", "true", "null", "TypeError"],
                correct: 1
            },
            {
                question: "Which statement about JavaScript closures is true?",
                answers: [
                    "Closures allow outer functions to access inner function variables",
                    "A closure is formed when an inner function accesses variables in its outer lexical scope",
                    "Closures only work with global variables",
                    "Arrow functions cannot form closures"
                ],
                correct: 1
            }
        ],
        hard: [
            {
                question: "What is the output of `console.log([] == ![])`?",
                answers: ["false", "true", "TypeError", "NaN"],
                correct: 1
            },
            {
                question: "How does the JavaScript runtime handle asynchronous execution in the event loop?",
                answers: [
                    "Microtasks (Promises) are executed after every individual macrotask (timers)",
                    "Macrotasks are executed continuously before microtasks are emptied",
                    "Microtasks and macrotasks run concurrently on separate threads",
                    "Microtask queue is only checked when the call stack has 2 or more frames"
                ],
                correct: 0
            },
            {
                question: "What is the purpose of `Object.freeze()` compared to `Object.seal()`?",
                answers: [
                    "freeze allows mutating existing properties; seal prevents all mutations",
                    "freeze makes properties read-only and non-configurable; seal prevents adding/deleting properties but allows modifying existing writable values",
                    "seal prevents modifying object prototypes; freeze affects only top-level properties",
                    "They are identical alias functions in ES6"
                ],
                correct: 1
            },
            {
                question: "Which behavior occurs during the hoisting phase for functions declared with function declarations vs function expressions assigned to `var`?",
                answers: [
                    "Function declarations are hoisted completely; var expressions are hoisted with value `undefined`",
                    "Both are hoisted with their complete function implementation",
                    "Function expressions are hoisted; declarations trigger ReferenceError",
                    "Neither is hoisted in strict mode"
                ],
                correct: 0
            },
            {
                question: "What does the `Symbol` primitive type guarantee in JavaScript?",
                answers: [
                    "It converts strings to unique numbers",
                    "It produces an absolutely unique identifier",
                    "It encrypts object property values",
                    "It automatically freezes object properties"
                ],
                correct: 1
            },
            {
                question: "What will `console.log(1 + - + + + - 1)` evaluate to?",
                answers: ["0", "2", "NaN", "-2"],
                correct: 1
            },
            {
                question: "In ES6 classes, what must be called before accessing `this` inside a derived subclass constructor?",
                answers: ["this.init()", "super()", "parent()", "Object.assign(this)"],
                correct: 1
            },
            {
                question: "What is the output of `typeof (function(){})()`?",
                answers: ["function", "object", "undefined", "string"],
                correct: 2
            },
            {
                question: "What is a major characteristic of a JavaScript `WeakMap`?",
                answers: [
                    "Keys must be primitive types",
                    "Keys are weakly held and must be objects, allowing garbage collection if no other references exist",
                    "It maintains explicit insertion order when iterating over keys",
                    "It supports full length inspection via a .size property"
                ],
                correct: 1
            },
            {
                question: "What does `Reflect.apply(target, thisArgument, argumentsList)` do?",
                answers: [
                    "Applies styling to DOM elements",
                    "Calls a target function with specified arguments and `this` value",
                    "Clones an object using reflective inheritance",
                    "Traps getter and setter operations on a Proxy"
                ],
                correct: 1
            },
            {
                question: "Which static method returns a single Promise that resolves or rejects as soon as one of the promises resolves or rejects?",
                answers: ["Promise.all()", "Promise.any()", "Promise.race()", "Promise.allSettled()"],
                correct: 2
            },
            {
                question: "What is the output of `console.log(1 < 2 < 3)` and `console.log(3 > 2 > 1)`?",
                answers: [
                    "true and true",
                    "true and false",
                    "false and false",
                    "false and true"
                ],
                correct: 1
            },
            {
                question: "How does `Proxy` intercept object property lookup in JavaScript?",
                answers: [
                    "Using the `get` trap",
                    "Using the `lookup` trap",
                    "Using the `read` trap",
                    "Using the `fetch` trap"
                ],
                correct: 0
            },
            {
                question: "What is the result of `Object.is(-0, +0)`?",
                answers: ["true", "false", "undefined", "TypeError"],
                correct: 1
            },
            {
                question: "Which flag in `Object.defineProperty()` determines if a property can be deleted or its attributes changed?",
                answers: ["writable", "enumerable", "configurable", "mutable"],
                correct: 2
            },
            {
                question: "What does `String.prototype.normalize('NFC')` accomplish?",
                answers: [
                    "Converts string to standard ASCII",
                    "Performs Unicode Canonical Decomposition followed by Canonical Composition",
                    "Strips all whitespace and special characters",
                    "Converts string to lower-case UTF-8 encoding"
                ],
                correct: 1
            },
            {
                question: "What is the default binding phase for event listeners added via `addEventListener('click', handler)`?",
                answers: ["Capturing phase", "Target phase", "Bubbling phase", "Delegation phase"],
                correct: 2
            },
            {
                question: "What is the output of `(function(x) { delete x; return x; })(1)`?",
                answers: ["undefined", "1", "null", "ReferenceError"],
                correct: 1
            },
            {
                question: "Which JavaScript feature allows matching structured string formats using pattern expressions and returning capture groups directly?",
                answers: ["RegExp.prototype.exec()", "JSON.match()", "String.prototype.concat()", "Array.prototype.reduce()"],
                correct: 0
            },
            {
                question: "What will `console.log(a); var a = 10;` output?",
                answers: ["10", "ReferenceError", "undefined", "null"],
                correct: 2
            }
        ]
    },
    html: {
        easy: [
            {
                question: "What does HTML stand for?",
                answers: [
                    "Hyper Text Markup Language",
                    "High Tech Modern Language",
                    "Hyperlink Text Management Language",
                    "Home Tool Markup Language"
                ],
                correct: 0
            },
            {
                question: "Which tag is used to define the largest heading in HTML?",
                answers: ["<h6>", "<head>", "<h1>", "<heading>"],
                correct: 2
            },
            {
                question: "Which HTML element is used to insert a line break?",
                answers: ["<lb>", "<br>", "<break>", "<line>"],
                correct: 1
            },
            {
                question: "Which attribute is used to provide an alternate text for an image?",
                answers: ["title", "src", "alt", "description"],
                correct: 2
            },
            {
                question: "Which element is used to create a hyperlink in HTML?",
                answers: ["<a>", "<link>", "<href>", "<url>"],
                correct: 0
            },
            {
                question: "Which HTML tag is used to create an unordered list?",
                answers: ["<ol>", "<ul>", "<list>", "<li>"],
                correct: 1
            },
            {
                question: "Which HTML tag is used to define an input control in a form?",
                answers: ["<form>", "<input>", "<textfield>", "<entry>"],
                correct: 1
            },
            {
                question: "What is the correct tag for making text bold in modern semantic HTML?",
                answers: ["<b>", "<strong>", "<bold>", "<heavy>"],
                correct: 1
            },
            {
                question: "Which character is used to indicate an end tag in HTML?",
                answers: ["^", "/", "<", "*"],
                correct: 1
            },
            {
                question: "Where in an HTML document is the correct place to refer to an external style sheet?",
                answers: ["At the end of document", "In the <body> section", "In the <head> section", "Inside the <footer> section"],
                correct: 2
            }
        ],
        medium: [
            {
                question: "Which HTML5 element is specifically designed to contain independent, self-contained content like blog posts?",
                answers: ["<section>", "<article>", "<aside>", "<div>"],
                correct: 1
            },
            {
                question: "What is the difference between `<script async>` and `<script defer>`?",
                answers: [
                    "async executes script after HTML parsing; defer executes as soon as script downloads",
                    "async downloads in background and executes immediately upon download; defer executes after document parsing completes",
                    "defer can only be used for external CSS files",
                    "async blocks DOM parsing while defer does not download until DOMContentLoaded triggers"
                ],
                correct: 1
            },
            {
                question: "Which attribute opens a linked document in a new browser tab or window?",
                answers: ["target='_self'", "target='_blank'", "target='_new'", "target='_parent'"],
                correct: 1
            },
            {
                question: "What is the primary function of the `<picture>` element in HTML5?",
                answers: [
                    "To display animated GIFs",
                    "To provide responsive image sources tailored to screen sizes/formats",
                    "To render 3D canvas graphics",
                    "To wrap img tags with dynamic CSS borders"
                ],
                correct: 1
            },
            {
                question: "Which tag is used to embed SVG code directly into an HTML document?",
                answers: ["<vector>", "<svg>", "<graphics>", "<canvas>"],
                correct: 1
            },
            {
                question: "What does the `required` attribute do when placed on a form input element?",
                answers: [
                    "Forces user to input numbers only",
                    "Prevents form submission if the input field is empty",
                    "Makes the field read-only",
                    "Automatically focuses the field on load"
                ],
                correct: 1
            },
            {
                question: "Which semantic HTML tag should be used to wrap a group of navigation links?",
                answers: ["<header>", "<nav>", "<links>", "<menu>"],
                correct: 1
            },
            {
                question: "What is the purpose of the `<fieldset>` element?",
                answers: [
                    "To create dynamic tables",
                    "To group related elements in a form",
                    "To define external data connections",
                    "To restrict field text lengths"
                ],
                correct: 1
            },
            {
                question: "Which input type provides a slider control in HTML5?",
                answers: ["type='slider'", "type='range'", "type='scroll'", "type='meter'"],
                correct: 1
            },
            {
                question: "What is the primary usage of the HTML `<template>` element?",
                answers: [
                    "To display fallback content for outdated browsers",
                    "To store HTML markup that is not rendered immediately, but can be instantiated via JavaScript",
                    "To define reusable CSS styles",
                    "To auto-populate form inputs"
                ],
                correct: 1
            },
            {
                question: "Which attribute specifies that an input field must be pre-selected when the page loads?",
                answers: ["active", "autofocus", "selected", "default"],
                correct: 1
            },
            {
                question: "What is the difference between `<em>` and `<i>` in HTML5?",
                answers: [
                    "<em> is purely stylistic; <i> adds strong structural emphasis",
                    "<em> indicates semantic stress emphasis; <i> represents text in an alternate voice or tone without extra stress",
                    "There is no difference; <em> is simply deprecated",
                    "<i> is only used for icons"
                ],
                correct: 1
            },
            {
                question: "Which tag defines scalable scalar measurement within a known range in HTML5?",
                answers: ["<progress>", "<meter>", "<scale>", "<range>"],
                correct: 1
            },
            {
                question: "How do you specify the character encoding for an HTML5 document?",
                answers: [
                    "<meta encoding='UTF-8'>",
                    "<meta charset='UTF-8'>",
                    "<header charset='UTF-8'>",
                    "<doctype charset='UTF-8'>"
                ],
                correct: 1
            },
            {
                question: "Which HTML attribute specifies an inline CSS style for an element?",
                answers: ["class", "style", "css", "font"],
                correct: 1
            }
        ],
        hard: [
            {
                question: "Which attribute on an `<iframe>` prevents loaded content from executing scripts or opening popups by default?",
                answers: ["security='strict'", "sandbox", "isolated", "crossorigin='deny'"],
                correct: 1
            },
            {
                question: "What is the purpose of the `rel='noopener noreferrer'` attribute on hyperlinks that open in a new tab?",
                answers: [
                    "It improves SEO indexing speeds",
                    "It prevents target page from accessing window.opener and stops referrer header leaks",
                    "It compresses target page bandwidth usage",
                    "It allows cross-origin script injection"
                ],
                correct: 1
            },
            {
                question: "What is the significance of the `is` attribute in standard HTML elements?",
                answers: [
                    "It acts as a boolean indicator for accessibility",
                    "It allows custom elements to extend standard HTML elements (Customized Built-in Elements)",
                    "It binds inline JavaScript variables directly to the element",
                    "It sets element priority during page rendering"
                ],
                correct: 1
            },
            {
                question: "Which Microdata attribute is used to define the item property in Schema.org HTML annotations?",
                answers: ["itemtype", "itemprop", "itemscope", "itemid"],
                correct: 1
            },
            {
                question: "What happens when an HTML browser encounters an unknown HTML tag like `<custom-tag>`?",
                answers: [
                    "It throws a DOMException error",
                    "It creates an HTMLUnknownElement instance and renders as inline display by default",
                    "It automatically strips the element from DOM",
                    "It blocks DOM rendering completely"
                ],
                correct: 1
            },
            {
                question: "Which ARIA attribute defines an element as a live region that announces updates immediately to screen readers regardless of user activity?",
                answers: ["aria-live='polite'", "aria-live='assertive'", "aria-atomic='true'", "aria-relevant='all'"],
                correct: 1
            },
            {
                question: "What is the main functional difference between `<dialog open>` and standard `<div>` elements?",
                answers: [
                    "dialog automatically centers content via CSS without flexbox",
                    "dialog provides built-in `.showModal()` API handling focus-trapping and top-layer rendering",
                    "dialog elements cannot be styled with CSS",
                    "div elements cannot contain form elements"
                ],
                correct: 1
            },
            {
                question: "What does the `loading='lazy'` attribute on an `<img>` tag instruct the browser to do?",
                answers: [
                    "Load image at lower resolution first",
                    "Defer loading the image until it reaches a calculated distance from the viewport",
                    "Load image only when requested via JavaScript click",
                    "Cache image permanently in local storage"
                ],
                correct: 1
            },
            {
                question: "Which HTTP header equivalent can be configured using `<meta http-equiv='...'>` in HTML?",
                answers: ["Content-Security-Policy", "Authorization", "Host", "User-Agent"],
                correct: 0
            },
            {
                question: "What is the function of the `<slot>` element in Shadow DOM?",
                answers: [
                    "To reserve layout space for lazy images",
                    "To act as a placeholder inside a Web Component shadow tree that gets filled by light DOM content",
                    "To load external Web Workers",
                    "To store localized key-value data"
                ],
                correct: 1
            },
            {
                question: "What is the effect of using `dir='auto'` attribute on an HTML text element?",
                answers: [
                    "It automatically aligns text horizontally center",
                    "It automatically sets text direction (LTR or RTL) based on character content",
                    "It forces text to wrap automatically",
                    "It converts all text to uppercase automatically"
                ],
                correct: 1
            },
            {
                question: "Which HTML tag is used to specify alternate resources for video/audio elements depending on codecs/media queries?",
                answers: ["<track>", "<source>", "<media>", "<alt>"],
                correct: 1
            },
            {
                question: "What does the `hidden='until-found'` attribute value enable in modern browsers?",
                answers: [
                    "Hides element permanently from DOM searches",
                    "Hides content visually but makes it searchable via Find-in-Page, revealing content when matched",
                    "Hides content until user authenticates",
                    "Hides content until screen width exceeds 768px"
                ],
                correct: 1
            },
            {
                question: "Which attribute on a form specifies how form data should be encoded when submitting it using POST method?",
                answers: ["enctype", "method", "action", "novalidate"],
                correct: 0
            },
            {
                question: "What is the purpose of the `<base>` tag in an HTML document's `<head>`?",
                answers: [
                    "Specifies base styling variables for CSS",
                    "Specifies the base URL/target for all relative URLs in a document",
                    "Defines fallback fonts for typography",
                    "Sets base screen zoom levels"
                ],
                correct: 1
            },
            {
                question: "In HTML forms, what is the behavior of `<input type='submit' formnovalidate>`?",
                answers: [
                    "It disables JavaScript events on submit",
                    "It submits form data without triggering HTML browser form validation checks",
                    "It converts form data to JSON format automatically",
                    "It prevents form data from being transmitted over HTTP"
                ],
                correct: 1
            },
            {
                question: "What does `aria-hidden='true'` do on an HTML element?",
                answers: [
                    "Visually hides the element from the display screen",
                    "Removes the element from the accessibility tree while keeping it visually visible",
                    "Completely removes element from DOM tree",
                    "Prevents pointer events on the element"
                ],
                correct: 1
            },
            {
                question: "What is the main role of the `<track>` element inside `<video>` tags?",
                answers: [
                    "Track analytics view counts",
                    "Specify timed text tracks like subtitles or captions",
                    "Track user playback position",
                    "Select video bitrate stream"
                ],
                correct: 1
            },
            {
                question: "Which `rel` link value tells browsers to pre-fetch resources needed for the next navigation?",
                answers: ["preload", "dns-prefetch", "prefetch", "prerender"],
                correct: 2
            },
            {
                question: "What is the correct syntax for declaring custom data attributes in HTML5?",
                answers: ["data-*", "custom-*", "attr-*", "var-*"],
                correct: 0
            }
        ]
    },
    css: {
        easy: [
            {
                question: "What does CSS stand for?",
                answers: [
                    "Cascading Style Sheets",
                    "Creative Style System",
                    "Computer Style Sheets",
                    "Colorful Style Syntax"
                ],
                correct: 0
            },
            {
                question: "Which CSS property is used to change the background color of an element?",
                answers: ["color", "background-color", "bgcolor", "canvas-color"],
                correct: 1
            },
            {
                question: "How do you select an element with `id='header'` in CSS?",
                answers: [".header", "header", "#header", "*header"],
                correct: 2
            },
            {
                question: "Which CSS property controls the text size?",
                answers: ["text-style", "font-size", "text-size", "font-height"],
                correct: 1
            },
            {
                question: "What is the default value of the `position` property in CSS?",
                answers: ["relative", "absolute", "static", "fixed"],
                correct: 2
            },
            {
                question: "Which CSS property is used to make text bold?",
                answers: ["font-weight", "text-decoration", "font-style", "font-bold"],
                correct: 0
            },
            {
                question: "How do you select all `<p>` elements inside a `<div>` in CSS?",
                answers: ["div + p", "div p", "div.p", "div > p only"],
                correct: 1
            },
            {
                question: "Which property is used to change the font of an element?",
                answers: ["font-family", "font-style", "font-type", "typeface"],
                correct: 0
            },
            {
                question: "How do you make a list render without bullet points in CSS?",
                answers: [
                    "list-style-type: none;",
                    "bullet-style: hidden;",
                    "text-decoration: no-bullets;",
                    "list-type: plain;"
                ],
                correct: 0
            },
            {
                question: "Which property controls the space between the content and the border of an element?",
                answers: ["margin", "padding", "spacing", "border-spacing"],
                correct: 1
            }
        ],
        medium: [
            {
                question: "What is the difference between `display: none` and `visibility: hidden`?",
                answers: [
                    "display: none hides element but keeps space; visibility: hidden removes from document layout completely",
                    "display: none removes element from document layout; visibility: hidden hides element but reserves space",
                    "They function identically",
                    "visibility: hidden prevents click events, display: none allows click events"
                ],
                correct: 1
            },
            {
                question: "What does `box-sizing: border-box` do?",
                answers: [
                    "Adds extra borders to elements automatically",
                    "Includes padding and border in the element's total width and height calculations",
                    "Forces margin space inside borders",
                    "Centers box on the screen"
                ],
                correct: 1
            },
            {
                question: "In CSS Flexbox, which property aligns items along the main axis?",
                answers: ["align-items", "justify-content", "align-content", "flex-direction"],
                correct: 1
            },
            {
                question: "What is the specificity value order in CSS (highest to lowest priority)?",
                answers: [
                    "Inline styles > IDs > Classes/Attributes/Pseudo-classes > Elements/Pseudo-elements",
                    "IDs > Inline styles > Classes > Elements",
                    "Classes > IDs > Elements > Inline styles",
                    "Elements > Classes > IDs > Inline styles"
                ],
                correct: 0
            },
            {
                question: "Which CSS Grid property creates responsive equal columns without media queries when combined with `minmax()`?",
                answers: [
                    "grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));",
                    "grid-auto-flow: dense;",
                    "grid-columns: flex-fit(200px);",
                    "grid-template-rows: auto-fill;"
                ],
                correct: 0
            },
            {
                question: "What value of `position` places an element relative to its nearest positioned ancestor?",
                answers: ["fixed", "absolute", "relative", "sticky"],
                correct: 1
            },
            {
                question: "What does the pseudo-class `:nth-child(2n)` select?",
                answers: [
                    "Every 2nd child element (even numbered elements)",
                    "Only the 2nd child element",
                    "Every odd child element",
                    "The last 2 child elements"
                ],
                correct: 0
            },
            {
                question: "Which CSS property controls item stacking order along the Z-axis?",
                answers: ["z-index", "depth", "layer", "order"],
                correct: 0
            },
            {
                question: "What unit in CSS is relative to the root element's (`<html>`) font size?",
                answers: ["em", "rem", "vh", "px"],
                correct: 1
            },
            {
                question: "What is the function of CSS `calc()`?",
                answers: [
                    "Calculates element display speed",
                    "Performs calculations to determine CSS property values dynamically",
                    "Counts total DOM elements in CSS",
                    "Calculates font weight averages"
                ],
                correct: 1
            },
            {
                question: "Which CSS property handles text wrapping when words exceed line length bounds?",
                answers: ["word-break / overflow-wrap", "text-wrap-mode", "line-break-force", "white-space-cut"],
                correct: 0
            },
            {
                question: "How does `position: sticky` behave?",
                answers: [
                    "It sticks permanently to top-left corner of screen",
                    "Treated as relative until a given scroll threshold is met, then behaves like fixed",
                    "Sticks elements together with zero margins",
                    "Works only inside CSS Grid structures"
                ],
                correct: 1
            },
            {
                question: "Which property adjusts image or video scaling to fit inside container bounds while maintaining aspect ratio?",
                answers: ["object-fit", "background-size-mode", "aspect-ratio-fit", "image-scale"],
                correct: 0
            },
            {
                question: "What is the result of applying `flex-grow: 1` on flex items?",
                answers: [
                    "Forces item width to 100px",
                    "Allows items to grow equally to fill available free space in flex container",
                    "Shrinks items when screen scales down",
                    "Prevents item wrap"
                ],
                correct: 1
            },
            {
                question: "Which media query detects dark mode preference on user devices?",
                answers: [
                    "@media (color-scheme: dark)",
                    "@media (prefers-color-scheme: dark)",
                    "@media (theme: dark)",
                    "@media (dark-mode: active)"
                ],
                correct: 1
            }
        ],
        hard: [
            {
                question: "What is a Block Formatting Context (BFC) and which property combination creates one?",
                answers: [
                    "Layout context created by display: inline",
                    "Independent layout region where margin collapsing doesn't occur; created by display: flow-root or overflow: hidden",
                    "CSS layout used exclusively for printing media",
                    "Context created only by flexbox items"
                ],
                correct: 1
            },
            {
                question: "How does the `contain` CSS property improve rendering performance?",
                answers: [
                    "Compresses CSS bundle sizes dynamically",
                    "Allows isolating elements from DOM tree layout, style, and paint calculations",
                    "Enforces single-thread rendering",
                    "Prevents external fonts from rendering"
                ],
                correct: 1
            },
            {
                question: "What does the `:has()` selector in modern CSS enable?",
                answers: [
                    "Parent / previous sibling filtering based on descendent condition match",
                    "Checking if an element has JavaScript attached",
                    "Validating HTML form input attributes",
                    "Matching elements with specified CSS variables"
                ],
                correct: 0
            },
            {
                question: "What occurs during vertical margin collapsing in standard flow layout?",
                answers: [
                    "Adjacent margins sum together",
                    "Adjacent top/bottom margins collapse into a single margin equal to the largest margin",
                    "Margins are converted to padding automatically",
                    "Margins trigger horizontal scrollbars"
                ],
                correct: 1
            },
            {
                question: "What is the exact function of `will-change` property in CSS?",
                answers: [
                    "Applies smooth transition to future CSS states",
                    "Gives browser early hint to optimize GPU hardware acceleration layers ahead of actual changes",
                    "Forces immediate DOM re-render",
                    "Triggers CSS variable animations"
                ],
                correct: 1
            },
            {
                question: "What is the computed value of `width: clamp(200px, 50vw, 500px)` on a viewport 800px wide?",
                answers: ["200px", "400px", "500px", "300px"],
                correct: 1
            },
            {
                question: "In CSS Container Queries, which property setups element containment context?",
                answers: [
                    "container-type: inline-size;",
                    "containment-query: container;",
                    "media-container: query;",
                    "display: container-box;"
                ],
                correct: 0
            },
            {
                question: "What is the difference between `@layer` (Cascade Layers) and standard CSS rules?",
                answers: [
                    "Cascade layers govern order of precedence regardless of selector specificity within rules",
                    "Cascade layers only apply to animations",
                    "Cascade layers bypass HTML parsing completely",
                    "Cascade layers increase element z-index values automatically"
                ],
                correct: 0
            },
            {
                question: "What happens when using `transform: translate3d(0, 0, 0)` on an element?",
                answers: [
                    "Moves element 30 pixels right",
                    "Triggers browser GPU compositing layer creation for potential performance optimization",
                    "Resets element aspect ratio",
                    "Rotates element in 3D space"
                ],
                correct: 1
            },
            {
                question: "Which pseudo-element targets custom scrollbars in WebKit browsers?",
                answers: [
                    "::scroll-bar",
                    "::-webkit-scrollbar",
                    "::custom-scroll",
                    "::scrollbar-thumb"
                ],
                correct: 1
            },
            {
                question: "What is the behavior of `pointer-events: none` on an element?",
                answers: [
                    "Makes element invisible",
                    "Prevents element from becoming mouse/touch event targets, passing events to elements underneath",
                    "Disables user typing inputs",
                    "Removes cursor icon from screen"
                ],
                correct: 1
            },
            {
                question: "How does `isolation: isolate` affect stacking contexts?",
                answers: [
                    "Removes element from standard CSS layout",
                    "Creates a new stacking context without requiring explicit position/z-index properties",
                    "Prevents child elements from executing transitions",
                    "Isolates flexbox items from container grid alignment"
                ],
                correct: 1
            },
            {
                question: "What does the `subgrid` value inside `grid-template-columns` do?",
                answers: [
                    "Creates a nested sub-table",
                    "Allows nested grid item to inherit track definitions from parent grid",
                    "Splits grid columns into 2 equal halves",
                    "Disables gap parameters"
                ],
                correct: 1
            },
            {
                question: "What is the specificity value of selector `#nav ul.menu li a:hover`?",
                answers: [
                    "(1, 2, 2) -> 1 ID, 2 Classes/pseudo-classes, 2 Elements",
                    "(0, 3, 2)",
                    "(1, 1, 3)",
                    "(2, 0, 2)"
                ],
                correct: 0
            },
            {
                question: "Which CSS feature allows defining fallback values when CSS variables are missing (`var(--main-color, #fff)`)?",
                answers: [
                    "CSS Custom Property Fallbacks",
                    "CSS Conditionals",
                    "Media Feature Fallbacks",
                    "Cascade Overrides"
                ],
                correct: 0
            },
            {
                question: "What is the primary visual function of `backdrop-filter` in CSS?",
                answers: [
                    "Applies graphical effects like blur/color-shift to area behind element",
                    "Filters images inside container borders",
                    "Creates drop shadows under buttons",
                    "Changes page background image opacity"
                ],
                correct: 0
            },
            {
                question: "What does `mix-blend-mode` control?",
                answers: [
                    "How an element's content blends with content of element's direct parent/background",
                    "How audio levels blend in HTML5 audio tags",
                    "How CSS variables merge across stylesheets",
                    "How font weights mix together"
                ],
                correct: 0
            },
            {
                question: "Which CSS layout property prevents grid tracks from shrinking below minimum size while taking flexible space?",
                answers: ["minmax()", "clamp()", "fit-content()", "repeat()"],
                correct: 0
            },
            {
                question: "What is the purpose of `@supports` rule in CSS?",
                answers: [
                    "Checks if user browser supports specific CSS property-value pairs (Feature Queries)",
                    "Loads external library support scripts",
                    "Tests web accessibility compliance",
                    "Validates CSS syntax for errors"
                ],
                correct: 0
            },
            {
                question: "What is the behavior of `font-display: swap` in @font-face rules?",
                answers: [
                    "Swaps font colors dynamically",
                    "Instructs browser to use fallback system font immediately, swapping to custom font once loaded",
                    "Swaps uppercase and lowercase characters",
                    "Prevents custom web fonts from loading"
                ],
                correct: 1
            }
        ]
    },
    general: {
        easy: [
            {
                question: "What is the capital city of France?",
                answers: ["London", "Berlin", "Paris", "Madrid"],
                correct: 2
            },
            {
                question: "Which planet is known as the Red Planet?",
                answers: ["Venus", "Mars", "Jupiter", "Saturn"],
                correct: 1
            },
            {
                question: "What is the largest ocean on Earth?",
                answers: ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"],
                correct: 2
            },
            {
                question: "Who painted the Mona Lisa?",
                answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"],
                correct: 1
            },
            {
                question: "What chemical element has the symbol 'O'?",
                answers: ["Gold", "Oxygen", "Osmium", "Hydrogen"],
                correct: 1
            },
            {
                question: "Which country is home to the Kangaroo?",
                answers: ["South Africa", "Brazil", "Australia", "India"],
                correct: 2
            },
            {
                question: "How many continents are there on Earth?",
                answers: ["5", "6", "7", "8"],
                correct: 2
            },
            {
                question: "What is the hardest natural substance known on Earth?",
                answers: ["Gold", "Iron", "Diamond", "Platinum"],
                correct: 2
            },
            {
                question: "Which instrument is used to measure atmospheric pressure?",
                answers: ["Thermometer", "Barometer", "Speedometer", "Hydrometer"],
                correct: 1
            },
            {
                question: "What year did World War II end?",
                answers: ["1918", "1939", "1945", "1950"],
                correct: 2
            }
        ],
        medium: [
            {
                question: "Which gas makes up the largest percentage of Earth's atmosphere?",
                answers: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Argon"],
                correct: 1
            },
            {
                question: "Who developed the general theory of relativity?",
                answers: ["Isaac Newton", "Albert Einstein", "Nikola Tesla", "Niels Bohr"],
                correct: 1
            },
            {
                question: "What is the longest river in the world?",
                answers: ["Amazon River", "Nile River", "Yangtze River", "Mississippi River"],
                correct: 1
            },
            {
                question: "In which year did humans first land on the Moon?",
                answers: ["1965", "1969", "1972", "1959"],
                correct: 1
            },
            {
                question: "What is the primary function of red blood cells in the human body?",
                answers: ["Fight infections", "Transport oxygen", "Clot blood", "Digest nutrients"],
                correct: 1
            },
            {
                question: "Which European city is famous for its ancient Colosseum?",
                answers: ["Athens", "Rome", "Vienna", "Naples"],
                correct: 1
            },
            {
                question: "What is the chemical formula for table salt?",
                answers: ["KCl", "NaCl", "H2O", "CO2"],
                correct: 1
            },
            {
                question: "Which organ in the human body produces insulin?",
                answers: ["Liver", "Pancreas", "Kidney", "Gallbladder"],
                correct: 1
            },
            {
                question: "Who wrote the play 'Romeo and Juliet'?",
                answers: ["Charles Dickens", "William Shakespeare", "Mark Twain", "Jane Austen"],
                correct: 1
            },
            {
                question: "What is the capital city of Japan?",
                answers: ["Kyoto", "Tokyo", "Osaka", "Hiroshima"],
                correct: 1
            },
            {
                question: "Which layer of Earth lies directly below the crust?",
                answers: ["Outer Core", "Mantle", "Inner Core", "Lithosphere"],
                correct: 1
            },
            {
                question: "What type of energy is stored in a battery?",
                answers: ["Thermal energy", "Chemical energy", "Kinetic energy", "Nuclear energy"],
                correct: 1
            },
            {
                question: "Which country gifted the Statue of Liberty to the United States?",
                answers: ["United Kingdom", "France", "Germany", "Spain"],
                correct: 1
            },
            {
                question: "What unit is used to measure electrical resistance?",
                answers: ["Volt", "Ohm", "Watt", "Ampere"],
                correct: 1
            },
            {
                question: "Which vitamin is synthesized when human skin is exposed to sunlight?",
                answers: ["Vitamin A", "Vitamin D", "Vitamin C", "Vitamin B12"],
                correct: 1
            }
        ],
        hard: [
            {
                question: "What is the smallest unit of life capable of carrying out all life processes independently?",
                answers: ["Tissue", "Cell", "Organelle", "Atom"],
                correct: 1
            },
            {
                question: "Which historical event was immediately triggered by the assassination of Archduke Franz Ferdinand in 1914?",
                answers: ["World War II", "World War I", "The Russian Revolution", "The Cold War"],
                correct: 1
            },
            {
                question: "What is the half-life of Carbon-14 used in radiocarbon dating (approximate)?",
                answers: ["1,200 years", "5,730 years", "10,500 years", "25,000 years"],
                correct: 1
            },
            {
                question: "Which noble gas has the atomic number 2?",
                answers: ["Neon", "Helium", "Argon", "Krypton"],
                correct: 1
            },
            {
                question: "Which deep sea trench is recognized as the deepest point in Earth's oceans?",
                answers: ["Puerto Rico Trench", "Mariana Trench", "Java Trench", "Tonga Trench"],
                correct: 1
            },
            {
                question: "Who was the first human to travel into outer space?",
                answers: ["Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "John Glenn"],
                correct: 1
            },
            {
                question: "What is the fundamental particle that carries electromagnetic force?",
                answers: ["Gluon", "Photon", "Boson", "Quark"],
                correct: 1
            },
            {
                question: "Which ancient civilization constructed the Machu Picchu citadel in Peru?",
                answers: ["Aztecs", "Inca", "Mayans", "Olmecs"],
                correct: 1
            },
            {
                question: "What is the capital city of Australia?",
                answers: ["Sydney", "Canberra", "Melbourne", "Brisbane"],
                correct: 1
            },
            {
                question: "Which enzyme in human saliva breaks down starches into simpler sugars?",
                answers: ["Pepsin", "Amylase", "Lipase", "Trypsin"],
                correct: 1
            },
            {
                question: "In physics, what does Hubble's Law measure?",
                answers: [
                    "The speed of sound in vacuum",
                    "The rate at which the universe is expanding",
                    "Gravitational constant shifts",
                    "Light refraction in optics"
                ],
                correct: 1
            },
            {
                question: "Which treaty signed in 1919 officially ended World War I?",
                answers: ["Treaty of Paris", "Treaty of Versailles", "Treaty of Ghent", "Treaty of Utrecht"],
                correct: 1
            },
            {
                question: "What is the main component of natural gas?",
                answers: ["Propane", "Methane", "Ethanol", "Butane"],
                correct: 1
            },
            {
                question: "Which African desert is the largest hot desert in the world?",
                answers: ["Kalahari Desert", "Sahara Desert", "Gobi Desert", "Atacama Desert"],
                correct: 1
            },
            {
                question: "Who formulated the three laws of planetary motion?",
                answers: ["Galileo Galilei", "Johannes Kepler", "Nicolaus Copernicus", "Edmond Halley"],
                correct: 1
            },
            {
                question: "What process do plants use to convert light energy into chemical energy?",
                answers: ["Respiration", "Photosynthesis", "Fermentation", "Transpiration"],
                correct: 1
            },
            {
                question: "Which mountain is the tallest peak above sea level on Earth?",
                answers: ["K2", "Mount Everest", "Mount Kilimanjaro", "Denali"],
                correct: 1
            },
            {
                question: "What is the speed of light in a vacuum (approximate)?",
                answers: ["150,000 km/s", "300,000 km/s", "500,000 km/s", "1,000,000 km/s"],
                correct: 1
            },
            {
                question: "Which country operates the Large Hadron Collider (LHC) at CERN across its border?",
                answers: ["Germany and Austria", "Switzerland and France", "Italy and France", "Belgium and Netherlands"],
                correct: 1
            },
            {
                question: "What is the SI unit of electric current?",
                answers: ["Volt", "Ampere", "Joule", "Watt"],
                correct: 1
            }
        ]
    }
};